#!/bin/bash -v
\rm -rf gen-py
\rm -rf gen_java
thrift --gen java bloomier.thrift
\mv gen-java gen_java
thrift --gen py bloomier.thrift 
chmod a+x gen-py/bloomier/UserHistory-remote
lein javac
lein jar
#lein repl
#lein run 9000 
#./test-thrift-interface
