#!/bin/bash -v
cd gen-py/bloomier
./UserHistory-remote -h localhost:9000 visit 20 10
./UserHistory-remote -h localhost:9000 visit 20 10
./UserHistory-remote -h localhost:9000 visit 20 10
./UserHistory-remote -h localhost:9000 visit 20 10
./UserHistory-remote -h localhost:9000 visit 20 10
./UserHistory-remote -h localhost:9000 visit 20 10
./UserHistory-remote -h localhost:9000 visit 30 20
./UserHistory-remote -h localhost:9000 visit 20 10
./UserHistory-remote -h localhost:9000 visit 30 30
./UserHistory-remote -h localhost:9000 count 20 10
./UserHistory-remote -h localhost:9000 count 30 20
./UserHistory-remote -h localhost:9000 count 30 30
